apiVersion: v1
kind: Service
metadata:
  name: nodeport-monitoring
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30001