apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  labels:
    app: purwadhika-webseite
    type: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purwadhika-webseite
  template:
    metadata:
      labels:
        app: purwadhika-webseite
        type: adminer
    spec: 
      containers:
        - name: adminer-database
          image: adminer
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-adminer
spec:
  selector:
    app: purwadhika-webseite
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30011