apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful
  labels:
    name: db-stateful
    app: purwadhika-website
    tier: dev
spec:
  # https://github.com/kubernetes/kubernetes/issues/69608
  serviceName: db-stateful-service
  replicas: 1
  selector:
    matchLabels:
      name: db-stateful
  volumeClaimTemplates:
    - metadata:
        name: db-stateful-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: linode-block-storage-retain
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      name: db-stateful
      labels:
        name: db-stateful
        app: purwadhika-website
        tier: dev
    spec:
      containers:
        - name: db-stateful
          image: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: db-stateful-volume-claim
              mountPath: /var/lib/mysql
            - name: config-map
              mountPath: /etc/mysql/conf.d/
              readOnly: true
          # command:
          #   - mysqld
          # args: 
          #   - --lower_case_table_names=1
          #   - --skip-ssl
          #   - mysqld 
          #   - --lower_case_table_names=1
          # command: 
          #   - bash
            # - cp /mnt/config-map/my.cnf /etc/mysql/conf.d
          # args: ["cp", "/mnt/config-map/my.cnf", "/etc/mysql/conf.d"]
      volumes:
        - name: config-map
          configMap:
            name: mysql-config

