apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
  namespace: purwadhika-web
  labels:
    app: purwadhika-website
    tier: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 10Gi